# Generated by Django 2.1.7 on 2019-03-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Inserte la direccion', max_length=64)),
                ('postal_code', models.CharField(help_text='Inserte el codigo postal', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Seleccione la fecha de entrada', null=True)),
                ('reference', models.CharField(max_length=11)),
                ('from_d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='From', to='application.Address')),
                ('to_d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='To', to='application.Address')),
            ],
        ),
    ]
