# Generated by Django 2.1.7 on 2019-05-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Inserte la direccion', max_length=64)),
                ('postal_code', models.CharField(help_text='Inserte el codigo postal', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('lives_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicili', to='application.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_cm', models.IntegerField()),
                ('width_cm', models.IntegerField()),
                ('height_cm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level_Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_max', models.IntegerField()),
                ('temp_min', models.IntegerField()),
                ('hum_max', models.IntegerField()),
                ('hum_min', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle', models.IntegerField()),
                ('shelf', models.IntegerField()),
                ('space', models.IntegerField()),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitat', to='application.Dimension')),
            ],
        ),
        migrations.CreateModel(
            name='Manifest',
            fields=[
                ('reference', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, help_text='Seleccione la fecha de entrada', null=True)),
                ('kind_manifest', models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=1)),
                ('from_d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='From', to='application.Address')),
                ('to_d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='To', to='application.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('delivery_date', models.DateField(blank=True, help_text='Seleccionar la fecha de salida', null=True)),
                ('client', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='es_de', to='application.Client')),
                ('level_agreement', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='te', to='application.Level_Agreement')),
                ('manifest', models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='es_troba', to='application.Manifest')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('temperatura', models.IntegerField()),
                ('ancho', models.IntegerField()),
                ('largo', models.IntegerField()),
                ('espacio_Total', models.IntegerField()),
                ('espacio_Ocupado', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esta', to='application.Room'),
        ),
        migrations.AddField(
            model_name='container',
            name='dimension_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='te', to='application.Dimension'),
        ),
        migrations.AddField(
            model_name='container',
            name='manifest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposa_de', to='application.Manifest'),
        ),
        migrations.AddField(
            model_name='container',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conte', to='application.Product'),
        ),
        migrations.AddField(
            model_name='container',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descarrega_a', to='application.Room'),
        ),
    ]
