# Generated by Django 2.1.7 on 2019-05-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='withdrawal',
        ),
    ]
