# Generated by Django 2.1.7 on 2019-03-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('delivery_date', models.DateField(blank=True, help_text='Seleccionar la fecha de salida', null=True)),
            ],
        ),
    ]
