# Generated by Django 2.1.7 on 2019-04-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='kind_manifest',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=1),
        ),
    ]
