# Generated by Django 2.1.7 on 2019-05-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manifest',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='es_troba', to='application.Manifest'),
        ),
    ]
