# Generated by Django 2.1.7 on 2019-03-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('lives_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domicili', to='application.Address')),
            ],
        ),
        migrations.AddField(
            model_name='producte',
            name='client',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, related_name='es_de', to='application.Client'),
        ),
    ]
