# Generated by Django 2.1.7 on 2019-05-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='desponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ocultar',
            field=models.BooleanField(default=False),
        ),
    ]
