# Generated by Django 2.1.7 on 2019-05-01 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_status', models.CharField(choices=[('M', 'Manteniment'), ('O', 'Operarios')], default='O', max_length=1)),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Realizando'), ('F', 'Finalizada')], default='P', max_length=1)),
                ('tipus', models.CharField(choices=[('B', 'Blanco'), ('V', 'Verde'), ('A', 'Azul')], default='V', max_length=1)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('gestorsala', 'gestor de sala'), ('operario', 'operario'), ('mantenimiento', 'operario de mantenimiento'), ('CEO', 'CEO')], default='operario', max_length=32)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manifest',
            name='kind_manifest',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Salida')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignado', to='application.UserProfile'),
        ),
    ]
