# Generated by Django 2.1.7 on 2019-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190520_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifest',
            name='creationDate',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='manifest',
            name='revisionDate',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='withdrawal',
            field=models.BooleanField(),
        ),
    ]
