# Generated by Django 2.1.7 on 2019-03-31 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190331_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicació',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasillo', models.IntegerField()),
                ('prestatge', models.IntegerField()),
                ('hueco', models.IntegerField()),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esta', to='application.Sala')),
            ],
        ),
    ]
