# Generated by Django 2.1.7 on 2019-04-26 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_manifest_kind_manifest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('gestorsala', 'gestor de sala'), ('operario', 'operario'), ('mantenimiento', 'operario de mantenimiento'), ('CEO', 'CEO')], default='operario', max_length=32)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
