# Generated by Django 2.1.7 on 2019-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='excel',
            field=models.FileField(default='default.png', upload_to='excel/'),
        ),
    ]
