# Generated by Django 2.1.7 on 2019-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190521_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manifest',
            name='date',
        ),
        migrations.AlterField(
            model_name='manifest',
            name='creationDate',
            field=models.DateField(blank=True, help_text='Seleccione la fecha de creación', null=True),
        ),
        migrations.AlterField(
            model_name='manifest',
            name='revisionDate',
            field=models.DateField(blank=True, help_text='Seleccione la fecha de revisión', null=True),
        ),
    ]
