# Generated by Django 2.1.7 on 2019-05-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='r_status',
            field=models.CharField(choices=[('F', 'Frio'), ('M', 'Mixto'), ('N', 'Normal')], default='N', max_length=1),
        ),
    ]
