# Generated by Django 2.1.7 on 2019-06-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_documents_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='excel',
            field=models.FileField(default='default-image.png', upload_to='excel/'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='graph',
            field=models.ImageField(default='default-image.png', upload_to='graph/'),
        ),
    ]
