# Generated by Django 2.1.7 on 2019-03-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_sala_ubicació'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasillo', models.IntegerField()),
                ('prestatge', models.IntegerField()),
                ('hueco', models.IntegerField()),
                ('dimensio_u', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacitat', to='application.Dimensio')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esta', to='application.Sala')),
            ],
        ),
        migrations.RemoveField(
            model_name='ubicació',
            name='sala',
        ),
        migrations.RenameField(
            model_name='container',
            old_name='dimensio',
            new_name='dimensio_c',
        ),
        migrations.DeleteModel(
            name='Ubicació',
        ),
    ]
