# Generated by Django 2.1.7 on 2019-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Realizando'), ('F', 'Finalizada')], default='P', max_length=1)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=256)),
            ],
        ),
    ]
