# Generated by Django 2.1.7 on 2019-03-31 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190331_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='descarrega_a', to='application.Sala'),
            preserve_default=False,
        ),
    ]
