# Generated by Django 2.1.7 on 2019-04-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20190428_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='t_status',
            field=models.CharField(choices=[('M', 'Manteniment'), ('O', 'Operarios')], default='O', max_length=1),
        ),
    ]
